---
- defaults:
    link:
      relink: true

- clean: ["~"]

- create:
    - ~/Git_Projects/Personal/GitHub
    - ~/Git_Projects/Personal/GitHub/mrlesmithjr
    - ~/Git_Projects/Personal/GitLab
    - ~/Git_Projects/Work
    - ~/Playground
    - ~/Projects

- link:
    ~/.bash_profile:
      path: .bash_profile
      force: true
    ~/.bashrc:
      path: .bashrc
      force: true
    ~/.config/yamllint/config:
      create: true
      path: .yamllint.yml
    ~/.gitconfig:
      path: .gitconfig
      force: true
    ~/.gitignore_global:
      path: .gitignore_global
    ~/.git-template:
      path: .git-template
    ~/.p10k.zsh:
      path: .p10k.zsh
    ~/.pylintrc:
      path: .pylintrc
    ~/.rubocop.yml:
      path: .rubocop.yml
    ~/.tmux.conf:
      path: .tmux.conf
    ~/.vim:
      path: .vim
    ~/.vimrc:
      path: .vimrc
    ~/.yamllint.yml:
      path: .yamllint.yml
    ~/.zshrc:
      path: .zshrc
      force: true

- shell:
    - command: git submodule update --init --recursive
      description: Installing submodules
    - command: if [ ! -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then git clone https://github.com/magicmonty/bash-git-prompt.git "$HOME/.bash-git-prompt" --depth=1; fi
      description: Installing bash-git-prompt
    - command: if [ ! -d "$HOME/.oh-my-zsh" ]; then git clone https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"; fi
      description: Installing oh-my-zsh
    - command: if [ ! -d "$HOME/powerlevel10k" ]; then git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME"/powerlevel10k; fi
      description: Installing Powerlevel10k
    - command: vim +BundleInstall +qall 2 &>/dev/null
      description: Installing VIM bundles
